# Generated by Django 5.2.2 on 2025-06-29 12:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_has_conclusion_article_has_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='articlesection',
            name='is_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='is_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='blog.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2099, 12, 31, 23, 59)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
