# Generated by Django 5.2.2 on 2025-07-19 21:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_published'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE blog_articlesection
            SET content = to_jsonb(content)::text
            WHERE content IS NOT NULL
              AND (content NOT LIKE '{%' AND content NOT LIKE '[%' AND content NOT LIKE '"%');
            """
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
