# Generated by Django 5.2.2 on 2025-07-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_set_jsonfield_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('published', 'Publié')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privé'), ('restricted', 'Réservé'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_impact', models.PositiveSmallIntegerField(default=0)),
                ('criteria_clarity', models.PositiveSmallIntegerField(default=0)),
                ('criteria_utility', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.article')),
            ],
        ),
    ]
