# Generated by Django 5.2.2 on 2025-07-20 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_featured_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
