# Generated by Django 5.2.2 on 2025-07-21 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articlesection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
