# Generated by Django 5.2.2 on 2025-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jared_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaredLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jaredtask',
            options={},
        ),
        migrations.AlterField(
            model_name='jaredmessage',
            name='context',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jaredmessage',
            name='recipient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jaredmessage',
            name='sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jaredtask',
            name='assigned_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jaredtask',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jaredtask',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('blocked', 'Bloquée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jaredtask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
