# Generated by Django 5.2.2 on 2025-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jared_dashboard', '0002_jaredlog_alter_jaredtask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaredConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
