# Generated by Django 5.2.2 on 2025-07-28 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jared_dashboard', '0003_jaredconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaredDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.TextField()),
                ('decision', models.TextField()),
                ('impact', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JaredDelegatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_name', models.CharField(max_length=100)),
                ('task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JaredHistoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('focus', models.CharField(blank=True, max_length=100)),
                ('findings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JaredKPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metrics', models.JSONField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JaredPrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JaredRoadmapUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_or_theme', models.CharField(max_length=100)),
                ('update', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JaredStrategicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
