# Generated by Django 5.2.2 on 2025-07-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jared_dashboard', '0004_jareddecisionlog_jareddelegatedtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('content', models.TextField(help_text='Contenu intégral du manifeste (Markdown ou format structuré)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, help_text='Un seul manifeste actif à la fois')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestoUpdateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by', models.CharField(help_text='Nom de l’agent ou personne proposant la mise à jour', max_length=100)),
                ('target_version', models.CharField(help_text='Version cible (ex: 1.1)', max_length=10)),
                ('section_reference', models.CharField(help_text='Référence ou extrait de la section ciblée', max_length=255)),
                ('proposed_change', models.TextField(help_text='Texte proposé pour remplacement ou ajout')),
                ('justification', models.TextField(help_text='Pourquoi cette modification ?')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('date_archived', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(max_length=100)),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='jared_dashboard.manifesto')),
            ],
        ),
    ]
